[package]
name = "win_proc_mem"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.54", features = [
  "Win32_System_Threading",
  "Win32_System_Memory",
  "Win32_Foundation"
]}
